"use client"
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import Head from 'next/head';
import { useEffect } from 'react';
import Providers from '@/utils/provider';
import AlertNotification from '../components/notifications';

/* export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} */

export default function RootLayout({ children }) {

  useEffect(() => {
    import('bootstrap/dist/js/bootstrap');
  }, []);

  return (
    <html lang="en">
      <Head>
        <meta charset="utf-8" />
        <meta name="author" content="Daniel Nwokocha" />
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
        <title>Peer to peer Giftcard Trading Platform</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"
        />
      </Head>
      <body>
        <main style={{height: "100vh"}} className='d-flex flex-column'>
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  )
}
