@baseUrl = http://localhost:3000/api/v1/

# @name getAllUsers
GET {{baseUrl}}/users HTTP/1.1

###

@userId = c48e091d-da07-4989-a920-75c8940f5ff9
# @name deleteUser
DELETE  {{baseUrl}}/users/{{userId}} HTTP/1.1

###
