
@baseUrl = http://localhost:3000/api/v1/

# @name getAllOffers
GET {{baseUrl}}/offers/all HTTP/1.1

###


# @name deleteOffer
@offerId = "aec2751f-346c-46a2-832b-647b01241e8c"
DELETE  {{baseUrl}}/offers/all/{{offerId}} HTTP/1.1
###





# @name getBranches
GET {{baseUrl}}/branch HTTP/1.1

###
@tradeId = f3b3e9b7-f969-4e2a-8bc3-63c99d4dcb1a

# @name getTrade
GET {{baseUrl}}/trades/{{tradeId}} HTTP/1.1

###

# @name updateTrade
PATCH  {{baseUrl}}/trades/{{tradeId}} HTTP/1.1
Content-Type: "application/json"

{
  "code": "test-code-updated"
}

###

# @name deleteTrade
DELETE  {{baseUrl}}/trades/{{tradeId}}
